
all:
	@gcc Solution_1.c -o solution_1

run: 
	@./solution_1 ${NAME}

clean: 
	@(rm solution_1)

usage:
	@echo "Use 'all' target or jsut type 'make' to compile the code."
	@echo "Use 'run NAME=<filename you want to open>' target to execute the code."
	@echo "Use 'clean' target to remove the executable file."
	@echo "Use 'usage' to print this section."
	
