
all:
	@gcc solution_2.c File_OP.c -o solution_2

run: 
	@./solution_2 ${NAME} ${MODE}

clean: 
	@(rm solution_2)

usage:
	@echo "Use 'all' target or jsut type 'make' to compile the code."
	@echo "Use 'run NAME=<filename you want to open> MODE = <Mode of the file>'\
	 target to execute the code."
	@echo "Use 'clean' target to remove the executable file."
	@echo "Use 'usage' to print this section."
	
